def Crypt(text):
    temp=[]
    text.append(1)
    text.append(2)
    for i in range(len(text)):
        if(text[i]=="a"):
            text[i]='?'
        if(text[i]==" "):
            text[i]='G'
        if(text[i]=="q"):
            text[i]='.'
        if(text[i]=="w"):
            text[i]='/'
        if(text[i]=="e"):
            text[i]='['
        if(text[i]=="r"):
            text[i]=']'
        if(text[i]=="t"):
            text[i]='^'
        if(text[i]=="y"):
            text[i]='&'
        if(text[i]=="u"):
            text[i]='#'
        if(text[i]=="i"):
            text[i]='!'
        if(text[i]=="o"):
            text[i]='@'
        if(text[i]=="p"):
            text[i]='$'
        if(text[i]=="s"):
            text[i]='%'
        if(text[i]=="d"):
            text[i]='*'
        if(text[i]=="f"):
            text[i]='('
        if(text[i]=="g"):
            text[i]='('
        if(text[i]=="h"):
            text[i]='+'
        if(text[i]=="j"):
            text[i]='Z'
        if(text[i]=="k"):
            text[i]='Q'
        if(text[i]=="l"):
            text[i]='T'
        if(text[i]=="z"):
            text[i]='F'
        if(text[i]=="x"):
            text[i]='O'
        if(text[i]=="c"):
            text[i]='x'
        if(text[i]=="v"):
            text[i]='`'
        if(text[i]=="b"):
            text[i]='~'
        if(text[i]=="n"):
            text[i]='2'
        if(text[i]=="m"):
            text[i]='7'
        temp.append(text[i])
        temp.reverse()
    return(temp)
def Decrypt(text):
    return(text)
